package com.zdredge.consistency.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.zdredge.consistency.domain.model.CheckInState
import com.zdredge.consistency.domain.model.Slot
import java.time.Instant
import java.time.LocalDate

/**
 * A row for every check-in that was *expected*. This is the denominator for response rate -- the
 * primary metric -- so without this table it is simply unmeasurable (architecture section 5). Rows
 * are generated by the rollover job, which is why that job failing silently is the worst failure
 * this app has.
 *
 * The unique index on (day_date, slot) says the thing the model means: a check-in was either
 * expected on a given day in a given slot or it was not, and two rows for one would double-count the
 * denominator.
 *
 * [answeredAt] is a timestamp; [dayDate] is a date. A check-in answered "not yet" stays ANSWERED
 * even if the deferral is never resolved -- the user did complete the check-in (scoring-cases A2.2)
 * -- and a LATE answer does not repair a MISSED one (A1.2). Neither of those is expressible if the
 * check-in's state is inferred from its answers, which is why it is stored.
 *
 * Schema note: one of the three ask-first guarded tables (docs/CLAUDE.md). Realises architecture
 * section 5 exactly.
 */
@Entity(
    tableName = "checkins",
    indices = [Index(value = ["day_date", "slot"], unique = true)],
)
data class CheckInEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,
    @ColumnInfo(name = "user_id")
    val userId: String,
    @ColumnInfo(name = "day_date")
    val dayDate: LocalDate,
    @ColumnInfo(name = "slot")
    val slot: Slot,
    @ColumnInfo(name = "scheduled_at")
    val scheduledAt: Instant,
    @ColumnInfo(name = "state")
    val state: CheckInState,
    @ColumnInfo(name = "answered_at")
    val answeredAt: Instant? = null,
    /** How many notifications have fired for this check-in: the fire plus its escalation repeats. */
    @ColumnInfo(name = "notify_attempts")
    val notifyAttempts: Int = 0,
)
